# -*- coding: utf-8 -*-
"""Ejercicio 2 Carrito de Compras

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1190RYjwh1zKf0EYoTmp0SOFM212sq-0X
"""

#Ejercicio N°2 Carrito de Compra - Marketplace
productos_marketplace = {
  "computadora":60000,
    "mouse":1500,
    "Teclado":2000,
    "auriculares":3500,
    "Monitor":20000, }
lista = {}
print("Los  productos de la tienda son los siguientes: ")
print(productos_marketplace)

continuar = True
while continuar:
        item = input("Ingrese el producto elegido en nuestra tienda:  ")
        precio = float(input("Introduce el precio de " + item+ ": "))
        lista[item] = precio
        continuar = input("¿Quieres añadir artículos a la lista (si/no) ? ") == "si"
coste = 0
print("Los artículos adquiridos son: ")
for item, precio in lista.items (): 
       print(item, "\t", precio)
       coste += precio
print("Costo Total: ", coste)